[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = {version = "0.29.0", features = ["socket"]}

geo = "0.28.0"
wkt = "0.11"
rstar = "0.12.0"
petgraph = "0.6.5"
svg = "0.18.0"
prost = "0.13.3"


[build-dependencies]
