[package]
name = "tp_per_fast"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = {version = "0.29.0", features = ["socket"]}

prost = "0.13"
# Only necessary if using Protobuf well-known types:
prost-types = "0.13"
signal-hook = "0.3.17"
geo = "0.28.0"
wkt = "0.11"

[build-dependencies]
prost-build = "0.13"
